### PR TITLE
Various

### PR DESCRIPTION
**Pull request by hdgarrood**
In addition to what's in #2, I also did:
- A couple of fixes in the FFI files to ensure `Eff` callbacks get called
- Add `fork`
- Add `ChildProcessExit` type which is a bit clearer about what it means
- Fix warnings

### CODE REVIEW

**Comment by hdgarrood** [comment]
Also, I've been working on pulp alongside this locally, and I've switched out Pulp's own set of bindings to `child_process` with these, and Pulp's (reasonably comprehensive) tests all pass. So I'm reasonably confident that this works, although I haven't exercised absolutely everything. Setting `gid` and `uid` of child processes is something I've missed out, for instance.

**Comment by hdgarrood** [comment]
I've pushed a couple more commits to https://github.com/purescript-node/purescript-node-child-process now, so I'm starting to think that maybe the most sensible course of action now would be to unregister the current version on the bower registry and register the one at purescript-node. Does that sound ok?

**Comment by joneshf** [comment]
> I've pushed a couple more commits to https://github.com/purescript-node/purescript-node-child-process now, so I'm starting to think that maybe the most sensible course of action now would be to unregister the current version on the bower registry and register the one at purescript-node. Does that sound ok?

Sounds good to me. Just unregistered it.

**Comment by hdgarrood** [comment]
Super, thanks!

**Pull request closed without merging**
